"""initial migration

Revision ID: a40fdf993a0c
Revises: 1c8ed90dfd8c
Create Date: 2020-05-26 23:55:44.853129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40fdf993a0c'
down_revision = '1c8ed90dfd8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('owner', sa.String(length=24), nullable=True))
    op.add_column('comments', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    op.drop_column('comments', 'timestamp')
    op.drop_column('comments', 'owner')
    # ### end Alembic commands ###
